{
  "swagger" : "2.0",
  "info" : {
    "description" : "An OpenAPI for EVE Online",
    "version" : "0.2.5",
    "title" : "EVE Swagger Interface"
  },
  "host" : "esi.tech.ccp.is",
  "basePath" : "/latest",
  "schemes" : [ "https" ],
  "paths" : {
    "/alliances/" : {
      "get" : {
        "tags" : [ "Live", "Alliance" ],
        "summary" : "List all alliances",
        "description" : "List all active player alliances\n\n---\n\nAlternate route: `/v1/alliances/`\n\nAlternate route: `/legacy/alliances/`\n\nAlternate route: `/dev/alliances/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_alliances"
      }
    },
    "/alliances/names/" : {
      "get" : {
        "tags" : [ "Live", "Alliance" ],
        "summary" : "Get alliance names",
        "description" : "Resolve a set of alliance IDs to alliance names\n\n---\n\nAlternate route: `/v1/alliances/names/`\n\nAlternate route: `/legacy/alliances/names/`\n\nAlternate route: `/dev/alliances/names/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_alliances_names"
      }
    },
    "/alliances/{alliance_id}/" : {
      "get" : {
        "tags" : [ "Live", "Alliance" ],
        "summary" : "Get alliance information",
        "description" : "Public information about an alliance\n\n---\n\nAlternate route: `/v2/alliances/{alliance_id}/`\n\nAlternate route: `/dev/alliances/{alliance_id}/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_alliances_alliance_id"
      }
    },
    "/alliances/{alliance_id}/corporations/" : {
      "get" : {
        "tags" : [ "Live", "Alliance" ],
        "summary" : "List alliance's corporations",
        "description" : "List all current member corporations of an alliance\n\n---\n\nAlternate route: `/v1/alliances/{alliance_id}/corporations/`\n\nAlternate route: `/legacy/alliances/{alliance_id}/corporations/`\n\nAlternate route: `/dev/alliances/{alliance_id}/corporations/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_alliances_alliance_id_corporations"
      }
    },
    "/alliances/{alliance_id}/icons/" : {
      "get" : {
        "tags" : [ "Live", "Alliance" ],
        "summary" : "Get alliance icon",
        "description" : "Get the icon urls for a alliance\n\n---\n\nAlternate route: `/v1/alliances/{alliance_id}/icons/`\n\nAlternate route: `/legacy/alliances/{alliance_id}/icons/`\n\nAlternate route: `/dev/alliances/{alliance_id}/icons/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_alliances_alliance_id_icons"
      }
    },
    "/characters/names/" : {
      "get" : {
        "tags" : [ "Live", "Character" ],
        "summary" : "Get character names",
        "description" : "Resolve a set of character IDs to character names\n\n---\n\nAlternate route: `/v1/characters/names/`\n\nAlternate route: `/legacy/characters/names/`\n\nAlternate route: `/dev/characters/names/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_characters_names"
      }
    },
    "/characters/{character_id}/" : {
      "get" : {
        "tags" : [ "Live", "Character" ],
        "summary" : "Get character's public information",
        "description" : "Public information about a character\n\n---\n\nAlternate route: `/v3/characters/{character_id}/`\n\nAlternate route: `/legacy/characters/{character_id}/`\n\nAlternate route: `/dev/characters/{character_id}/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_characters_character_id"
      }
    },
    "/characters/{character_id}/bookmarks/" : {
      "get" : {
        "tags" : [ "Bookmarks", "Live" ],
        "summary" : "List bookmarks",
        "description" : "List your character's personal bookmarks\n\n---\n\nAlternate route: `/v1/characters/{character_id}/bookmarks/`\n\nAlternate route: `/legacy/characters/{character_id}/bookmarks/`\n\nAlternate route: `/dev/characters/{character_id}/bookmarks/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_characters_character_id_bookmarks",
        "security" : [ {
          "evesso" : [ "esi-bookmarks.read_character_bookmarks.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/bookmarks/folders/" : {
      "get" : {
        "tags" : [ "Bookmarks", "Live" ],
        "summary" : "List bookmark folders",
        "description" : "List your character's personal bookmark folders\n\n---\n\nAlternate route: `/v1/characters/{character_id}/bookmarks/folders/`\n\nAlternate route: `/legacy/characters/{character_id}/bookmarks/folders/`\n\nAlternate route: `/dev/characters/{character_id}/bookmarks/folders/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_characters_character_id_bookmarks_folders",
        "security" : [ {
          "evesso" : [ "esi-bookmarks.read_character_bookmarks.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/calendar/" : {
      "get" : {
        "tags" : [ "Live", "Calendar" ],
        "summary" : "List calendar event summaries",
        "description" : "Get 50 event summaries from the calendar. If no event ID is given,\nthe resource will return the next 50 chronological event summaries\nfrom now. If an event ID is specified, it will return the next 50\nchronological event summaries from after that event.\n\n\n---\n\nAlternate route: `/v1/characters/{character_id}/calendar/`\n\nAlternate route: `/legacy/characters/{character_id}/calendar/`\n\nAlternate route: `/dev/characters/{character_id}/calendar/`\n\n\n---\n\nThis ro[...]",
        "operationId" : "get_characters_character_id_calendar",
        "security" : [ {
          "evesso" : [ "esi-calendar.read_calendar_events.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/calendar/{event_id}/" : {
      "get" : {
        "tags" : [ "Live", "Calendar" ],
        "summary" : "Get an event",
        "description" : "Get all the information for a specific event\n\n---\n\nAlternate route: `/v3/characters/{character_id}/calendar/{event_id}/`\n\nAlternate route: `/dev/characters/{character_id}/calendar/{event_id}/`\n\n\n---\n\nThis route is cached for up to 5 seconds",
        "operationId" : "get_characters_character_id_calendar_event_id",
        "security" : [ {
          "evesso" : [ "esi-calendar.read_calendar_events.v1" ]
        } ]
      },
      "put" : {
        "tags" : [ "Live", "Calendar" ],
        "summary" : "Respond to an event",
        "description" : "Set your response status to an event\n\n---\n\nAlternate route: `/v3/characters/{character_id}/calendar/{event_id}/`\n\nAlternate route: `/dev/characters/{character_id}/calendar/{event_id}/`\n",
        "operationId" : "put_characters_character_id_calendar_event_id",
        "security" : [ {
          "evesso" : [ "esi-calendar.respond_calendar_events.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/clones/" : {
      "get" : {
        "tags" : [ "Live", "Clones" ],
        "summary" : "Get clones",
        "description" : "A list of the character's clones\n\n---\n\nAlternate route: `/v2/characters/{character_id}/clones/`\n\nAlternate route: `/dev/characters/{character_id}/clones/`\n\n\n---\n\nThis route is cached for up to 120 seconds",
        "operationId" : "get_characters_character_id_clones",
        "security" : [ {
          "evesso" : [ "esi-clones.read_clones.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/corporationhistory/" : {
      "get" : {
        "tags" : [ "Live", "Character" ],
        "summary" : "Get corporation history",
        "description" : "Get a list of all the corporations a character has been a member of\n\n---\n\nAlternate route: `/v1/characters/{character_id}/corporationhistory/`\n\nAlternate route: `/legacy/characters/{character_id}/corporationhistory/`\n\nAlternate route: `/dev/characters/{character_id}/corporationhistory/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_characters_character_id_corporationhistory"
      }
    },
    "/characters/{character_id}/cspa/" : {
      "post" : {
        "tags" : [ "Live", "Character" ],
        "summary" : "Calculate a CSPA charge cost",
        "description" : "Takes a source character ID in the url and a set of target character ID's in the body, returns a CSPA charge cost\n\n---\n\nAlternate route: `/v3/characters/{character_id}/cspa/`\n\nAlternate route: `/legacy/characters/{character_id}/cspa/`\n\nAlternate route: `/dev/characters/{character_id}/cspa/`\n",
        "operationId" : "post_characters_character_id_cspa",
        "security" : [ {
          "evesso" : [ "esi-characters.read_contacts.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/killmails/recent/" : {
      "get" : {
        "tags" : [ "Killmails", "Live" ],
        "summary" : "List kills and losses",
        "description" : "Return a list of character's recent kills and losses\n\n---\n\nAlternate route: `/v1/characters/{character_id}/killmails/recent/`\n\nAlternate route: `/legacy/characters/{character_id}/killmails/recent/`\n\nAlternate route: `/dev/characters/{character_id}/killmails/recent/`\n\n\n---\n\nThis route is cached for up to 120 seconds",
        "operationId" : "get_characters_character_id_killmails_recent",
        "security" : [ {
          "evesso" : [ "esi-killmails.read_killmails.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/location/" : {
      "get" : {
        "tags" : [ "Location", "Live" ],
        "summary" : "Get character location",
        "description" : "Information about the characters current location. Returns the current solar system id, and also the current station or structure ID if applicable.\n\n---\n\nAlternate route: `/v1/characters/{character_id}/location/`\n\nAlternate route: `/legacy/characters/{character_id}/location/`\n\nAlternate route: `/dev/characters/{character_id}/location/`\n\n\n---\n\nThis route is cached for up to 5 seconds",
        "operationId" : "get_characters_character_id_location",
        "security" : [ {
          "evesso" : [ "esi-location.read_location.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/mail/" : {
      "get" : {
        "tags" : [ "Live", "Mail" ],
        "summary" : "Return mail headers",
        "description" : "Return the 50 most recent mail headers belonging to the character that match the query criteria. Queries can be filtered by label, and last_mail_id can be used to paginate backwards.\n\n---\n\nAlternate route: `/v1/characters/{character_id}/mail/`\n\nAlternate route: `/legacy/characters/{character_id}/mail/`\n\nAlternate route: `/dev/characters/{character_id}/mail/`\n\n\n---\n\nThis route is cached for up to 30 seconds",
        "operationId" : "get_characters_character_id_mail",
        "security" : [ {
          "evesso" : [ "esi-mail.read_mail.v1" ]
        } ]
      },
      "post" : {
        "tags" : [ "Live", "Mail" ],
        "summary" : "Send a new mail",
        "description" : "Create and send a new mail\n\n---\n\nAlternate route: `/v1/characters/{character_id}/mail/`\n\nAlternate route: `/legacy/characters/{character_id}/mail/`\n\nAlternate route: `/dev/characters/{character_id}/mail/`\n",
        "operationId" : "post_characters_character_id_mail",
        "security" : [ {
          "evesso" : [ "esi-mail.send_mail.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/mail/labels/" : {
      "get" : {
        "tags" : [ "Live", "Mail" ],
        "summary" : "Get mail labels and unread counts",
        "description" : "Return a list of the users mail labels, unread counts for each label and a total unread count.\n\n---\n\nAlternate route: `/v3/characters/{character_id}/mail/labels/`\n\nAlternate route: `/dev/characters/{character_id}/mail/labels/`\n\n\n---\n\nThis route is cached for up to 30 seconds",
        "operationId" : "get_characters_character_id_mail_labels",
        "security" : [ {
          "evesso" : [ "esi-mail.read_mail.v1" ]
        } ]
      },
      "post" : {
        "tags" : [ "Live", "Mail" ],
        "summary" : "Create a mail label",
        "description" : "Create a mail label\n\n---\n\nAlternate route: `/v2/characters/{character_id}/mail/labels/`\n\nAlternate route: `/legacy/characters/{character_id}/mail/labels/`\n\nAlternate route: `/dev/characters/{character_id}/mail/labels/`\n",
        "operationId" : "post_characters_character_id_mail_labels",
        "security" : [ {
          "evesso" : [ "esi-mail.organize_mail.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/mail/lists/" : {
      "get" : {
        "tags" : [ "Live", "Mail" ],
        "summary" : "Return mailing list subscriptions",
        "description" : "Return all mailing lists that the character is subscribed to\n\n\n---\n\nAlternate route: `/v1/characters/{character_id}/mail/lists/`\n\nAlternate route: `/legacy/characters/{character_id}/mail/lists/`\n\nAlternate route: `/dev/characters/{character_id}/mail/lists/`\n\n\n---\n\nThis route is cached for up to 120 seconds",
        "operationId" : "get_characters_character_id_mail_lists",
        "security" : [ {
          "evesso" : [ "esi-mail.read_mail.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/mail/{mail_id}/" : {
      "get" : {
        "tags" : [ "Live", "Mail" ],
        "summary" : "Return a mail",
        "description" : "Return the contents of an EVE mail\n\n---\n\nAlternate route: `/v1/characters/{character_id}/mail/{mail_id}/`\n\nAlternate route: `/legacy/characters/{character_id}/mail/{mail_id}/`\n\nAlternate route: `/dev/characters/{character_id}/mail/{mail_id}/`\n\n\n---\n\nThis route is cached for up to 30 seconds",
        "operationId" : "get_characters_character_id_mail_mail_id",
        "security" : [ {
          "evesso" : [ "esi-mail.read_mail.v1" ]
        } ]
      },
      "put" : {
        "tags" : [ "Live", "Mail" ],
        "summary" : "Update metadata about a mail",
        "description" : "Update metadata about a mail\n\n---\n\nAlternate route: `/v1/characters/{character_id}/mail/{mail_id}/`\n\nAlternate route: `/legacy/characters/{character_id}/mail/{mail_id}/`\n\nAlternate route: `/dev/characters/{character_id}/mail/{mail_id}/`\n",
        "operationId" : "put_characters_character_id_mail_mail_id",
        "security" : [ {
          "evesso" : [ "esi-mail.organize_mail.v1" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Live", "Mail" ],
        "summary" : "Delete a mail",
        "description" : "Delete a mail\n\n---\n\nAlternate route: `/v1/characters/{character_id}/mail/{mail_id}/`\n\nAlternate route: `/legacy/characters/{character_id}/mail/{mail_id}/`\n\nAlternate route: `/dev/characters/{character_id}/mail/{mail_id}/`\n",
        "operationId" : "delete_characters_character_id_mail_mail_id",
        "security" : [ {
          "evesso" : [ "esi-mail.organize_mail.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/portrait/" : {
      "get" : {
        "tags" : [ "Live", "Character" ],
        "summary" : "Get character portraits",
        "description" : "Get portrait urls for a character\n\n---\n\nAlternate route: `/v2/characters/{character_id}/portrait/`\n\nAlternate route: `/dev/characters/{character_id}/portrait/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_characters_character_id_portrait"
      }
    },
    "/characters/{character_id}/search/" : {
      "get" : {
        "tags" : [ "Live", "Search" ],
        "summary" : "Search on a string",
        "description" : "Search for entities that match a given sub-string.\n\n---\n\nAlternate route: `/v2/characters/{character_id}/search/`\n\nAlternate route: `/dev/characters/{character_id}/search/`\n",
        "operationId" : "get_characters_character_id_search",
        "security" : [ {
          "evesso" : [ "esi-search.search_structures.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/ship/" : {
      "get" : {
        "tags" : [ "Location", "Live" ],
        "summary" : "Get current ship",
        "description" : "Get the current ship type, name and id\n\n---\n\nAlternate route: `/v1/characters/{character_id}/ship/`\n\nAlternate route: `/legacy/characters/{character_id}/ship/`\n\nAlternate route: `/dev/characters/{character_id}/ship/`\n\n\n---\n\nThis route is cached for up to 5 seconds",
        "operationId" : "get_characters_character_id_ship",
        "security" : [ {
          "evesso" : [ "esi-location.read_ship_type.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/skillqueue/" : {
      "get" : {
        "tags" : [ "Live", "Skills" ],
        "summary" : "Get character's skill queue",
        "description" : "List the configured skill queue for the given character\n\n---\n\nAlternate route: `/v2/characters/{character_id}/skillqueue/`\n\nAlternate route: `/legacy/characters/{character_id}/skillqueue/`\n\nAlternate route: `/dev/characters/{character_id}/skillqueue/`\n\n\n---\n\nThis route is cached for up to 120 seconds",
        "operationId" : "get_characters_character_id_skillqueue",
        "security" : [ {
          "evesso" : [ "esi-skills.read_skillqueue.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/skills/" : {
      "get" : {
        "tags" : [ "Live", "Skills" ],
        "summary" : "Get character skills",
        "description" : "List all trained skills for the given character\n\n---\n\nAlternate route: `/v3/characters/{character_id}/skills/`\n\nAlternate route: `/dev/characters/{character_id}/skills/`\n\n\n---\n\nThis route is cached for up to 120 seconds",
        "operationId" : "get_characters_character_id_skills",
        "security" : [ {
          "evesso" : [ "esi-skills.read_skills.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/wallets/" : {
      "get" : {
        "tags" : [ "Live", "Wallet" ],
        "summary" : "List wallets and balances",
        "description" : "List your wallets and their balances. Characters typically have only one wallet, with wallet_id 1000 being the master wallet.\n\n---\n\nAlternate route: `/v1/characters/{character_id}/wallets/`\n\nAlternate route: `/legacy/characters/{character_id}/wallets/`\n\nAlternate route: `/dev/characters/{character_id}/wallets/`\n\n\n---\n\nThis route is cached for up to 120 seconds",
        "operationId" : "get_characters_character_id_wallets",
        "security" : [ {
          "evesso" : [ "esi-wallet.read_character_wallet.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/wallets/journal/" : {
      "get" : {
        "tags" : [ "Wallet", "Dummy" ],
        "summary" : "Get character wallet journal",
        "description" : "Returns the most recent 50 entries for the characters wallet journal. Optionally, takes an argument with a reference ID, and returns the prior 50 entries from the journal.\n\n---\n\nAlternate route: `/v1/characters/{character_id}/wallets/journal/`\n\nAlternate route: `/legacy/characters/{character_id}/wallets/journal/`\n\nAlternate route: `/dev/characters/{character_id}/wallets/journal/`\n",
        "operationId" : "get_characters_character_id_wallets_journal",
        "security" : [ {
          "evesso" : [ "esi-wallet.read_character_wallet.v1" ]
        } ]
      }
    },
    "/characters/{character_id}/wallets/transactions/" : {
      "get" : {
        "tags" : [ "Wallet", "Dummy" ],
        "summary" : "Get wallet transactions",
        "description" : "Gets the 50 most recent transactions in a characters wallet. Optionally, takes an argument with a transaction ID, and returns the prior 50 transactions\n\n---\n\nAlternate route: `/v1/characters/{character_id}/wallets/transactions/`\n\nAlternate route: `/legacy/characters/{character_id}/wallets/transactions/`\n\nAlternate route: `/dev/characters/{character_id}/wallets/transactions/`\n",
        "operationId" : "get_characters_character_id_wallets_transactions",
        "security" : [ {
          "evesso" : [ "esi-wallet.read_character_wallet.v1" ]
        } ]
      }
    },
    "/corporations/names/" : {
      "get" : {
        "tags" : [ "Live", "Corporation" ],
        "summary" : "Get corporation names",
        "description" : "Resolve a set of corporation IDs to corporation names\n\n---\n\nAlternate route: `/v1/corporations/names/`\n\nAlternate route: `/legacy/corporations/names/`\n\nAlternate route: `/dev/corporations/names/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_corporations_names"
      }
    },
    "/corporations/{corporation_id}/" : {
      "get" : {
        "tags" : [ "Live", "Corporation" ],
        "summary" : "Get corporation information",
        "description" : "Public information about a corporation\n\n---\n\nAlternate route: `/v2/corporations/{corporation_id}/`\n\nAlternate route: `/dev/corporations/{corporation_id}/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_corporations_corporation_id"
      }
    },
    "/corporations/{corporation_id}/alliancehistory/" : {
      "get" : {
        "tags" : [ "Live", "Corporation" ],
        "summary" : "Get alliance history",
        "description" : "Get a list of all the alliances a corporation has been a member of\n\n---\n\nAlternate route: `/v1/corporations/{corporation_id}/alliancehistory/`\n\nAlternate route: `/legacy/corporations/{corporation_id}/alliancehistory/`\n\nAlternate route: `/dev/corporations/{corporation_id}/alliancehistory/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_corporations_corporation_id_alliancehistory"
      }
    },
    "/corporations/{corporation_id}/bookmarks/" : {
      "get" : {
        "tags" : [ "Bookmarks", "Dummy" ],
        "summary" : "Dummy Endpoint, Please Ignore",
        "description" : "Dummy\n\n---\n\nAlternate route: `/v1/corporations/{corporation_id}/bookmarks/`\n\nAlternate route: `/legacy/corporations/{corporation_id}/bookmarks/`\n\nAlternate route: `/dev/corporations/{corporation_id}/bookmarks/`\n",
        "operationId" : "get_corporations_corporation_id_bookmarks"
      }
    },
    "/corporations/{corporation_id}/bookmarks/folders/" : {
      "get" : {
        "tags" : [ "Bookmarks", "Dummy" ],
        "summary" : "Dummy Endpoint, Please Ignore",
        "description" : "Dummy\n\n---\n\nAlternate route: `/v1/corporations/{corporation_id}/bookmarks/folders/`\n\nAlternate route: `/legacy/corporations/{corporation_id}/bookmarks/folders/`\n\nAlternate route: `/dev/corporations/{corporation_id}/bookmarks/folders/`\n",
        "operationId" : "get_corporations_corporation_id_bookmarks_folders"
      }
    },
    "/corporations/{corporation_id}/icons/" : {
      "get" : {
        "tags" : [ "Live", "Corporation" ],
        "summary" : "Get corporation icon",
        "description" : "Get the icon urls for a corporation\n\n---\n\nAlternate route: `/v1/corporations/{corporation_id}/icons/`\n\nAlternate route: `/legacy/corporations/{corporation_id}/icons/`\n\nAlternate route: `/dev/corporations/{corporation_id}/icons/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_corporations_corporation_id_icons"
      }
    },
    "/corporations/{corporation_id}/members/" : {
      "get" : {
        "tags" : [ "Live", "Corporation" ],
        "summary" : "Get corporation members",
        "description" : "Read the current list of members if the calling character is a member.\n\n---\n\nAlternate route: `/v2/corporations/{corporation_id}/members/`\n\nAlternate route: `/legacy/corporations/{corporation_id}/members/`\n\nAlternate route: `/dev/corporations/{corporation_id}/members/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_corporations_corporation_id_members",
        "security" : [ {
          "evesso" : [ "esi-corporations.read_corporation_membership.v1" ]
        } ]
      }
    },
    "/corporations/{corporation_id}/roles/" : {
      "get" : {
        "tags" : [ "Live", "Corporation" ],
        "summary" : "Get corporation members",
        "description" : "Return the roles of all members if the character has the personnel manager role or any grantable role.\n\n---\n\nAlternate route: `/v1/corporations/{corporation_id}/roles/`\n\nAlternate route: `/legacy/corporations/{corporation_id}/roles/`\n\nAlternate route: `/dev/corporations/{corporation_id}/roles/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_corporations_corporation_id_roles",
        "security" : [ {
          "evesso" : [ "esi-corporations.read_corporation_membership.v1" ]
        } ]
      }
    },
    "/corporations/{corporation_id}/wallets/" : {
      "get" : {
        "tags" : [ "Wallet", "Dummy" ],
        "summary" : "Dummy Endpoint, Please Ignore",
        "description" : "Dummy\n\n---\n\nAlternate route: `/v1/corporations/{corporation_id}/wallets/`\n\nAlternate route: `/legacy/corporations/{corporation_id}/wallets/`\n\nAlternate route: `/dev/corporations/{corporation_id}/wallets/`\n",
        "operationId" : "get_corporations_corporation_id_wallets"
      }
    },
    "/corporations/{corporation_id}/wallets/{wallet_id}/journal/" : {
      "get" : {
        "tags" : [ "Wallet", "Dummy" ],
        "summary" : "Dummy Endpoint, Please Ignore",
        "description" : "Dummy\n\n---\n\nAlternate route: `/v1/corporations/{corporation_id}/wallets/{wallet_id}/journal/`\n\nAlternate route: `/legacy/corporations/{corporation_id}/wallets/{wallet_id}/journal/`\n\nAlternate route: `/dev/corporations/{corporation_id}/wallets/{wallet_id}/journal/`\n",
        "operationId" : "get_corporations_corporation_id_wallets_wallet_id_journal"
      }
    },
    "/corporations/{corporation_id}/wallets/{wallet_id}/transactions/" : {
      "get" : {
        "tags" : [ "Wallet", "Dummy" ],
        "summary" : "Dummy Endpoint, Please Ignore",
        "description" : "Dummy\n\n---\n\nAlternate route: `/v1/corporations/{corporation_id}/wallets/{wallet_id}/transactions/`\n\nAlternate route: `/legacy/corporations/{corporation_id}/wallets/{wallet_id}/transactions/`\n\nAlternate route: `/dev/corporations/{corporation_id}/wallets/{wallet_id}/transactions/`\n",
        "operationId" : "get_corporations_corporation_id_wallets_wallet_id_transactions"
      }
    },
    "/incursions/" : {
      "get" : {
        "tags" : [ "Incursions", "Live" ],
        "summary" : "List incursions",
        "description" : "Return a list of current incursions\n\n---\n\nAlternate route: `/v1/incursions/`\n\nAlternate route: `/legacy/incursions/`\n\nAlternate route: `/dev/incursions/`\n\n\n---\n\nThis route is cached for up to 300 seconds",
        "operationId" : "get_incursions"
      }
    },
    "/killmails/{killmail_id}/{killmail_hash}/" : {
      "get" : {
        "tags" : [ "Killmails", "Live" ],
        "summary" : "Get a single killmail",
        "description" : "Return a single killmail from its ID and hash\n\n---\n\nAlternate route: `/v1/killmails/{killmail_id}/{killmail_hash}/`\n\nAlternate route: `/legacy/killmails/{killmail_id}/{killmail_hash}/`\n\nAlternate route: `/dev/killmails/{killmail_id}/{killmail_hash}/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_killmails_killmail_id_killmail_hash"
      }
    },
    "/markets/prices/" : {
      "get" : {
        "tags" : [ "Market", "Live" ],
        "summary" : "List market prices",
        "description" : "Return a list of prices\n\n---\n\nAlternate route: `/v1/markets/prices/`\n\nAlternate route: `/legacy/markets/prices/`\n\nAlternate route: `/dev/markets/prices/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_markets_prices"
      }
    },
    "/markets/{region_id}/history/" : {
      "get" : {
        "tags" : [ "Market", "Live" ],
        "summary" : "List historical market statistics in a region",
        "description" : "Return a list of historical market statistics for the specified type in a region\n\n---\n\nAlternate route: `/v1/markets/{region_id}/history/`\n\nAlternate route: `/legacy/markets/{region_id}/history/`\n\nAlternate route: `/dev/markets/{region_id}/history/`\n\n\n---\n\nThis route is cached for up to 300 seconds",
        "operationId" : "get_markets_region_id_history"
      }
    },
    "/markets/{region_id}/orders/" : {
      "get" : {
        "tags" : [ "Market", "Live" ],
        "summary" : "List orders in a region",
        "description" : "Return a list of orders in a region\n\n---\n\nAlternate route: `/v1/markets/{region_id}/orders/`\n\nAlternate route: `/legacy/markets/{region_id}/orders/`\n\nAlternate route: `/dev/markets/{region_id}/orders/`\n\n\n---\n\nThis route is cached for up to 300 seconds",
        "operationId" : "get_markets_region_id_orders"
      }
    },
    "/search/" : {
      "get" : {
        "tags" : [ "Live", "Search" ],
        "summary" : "Search on a string",
        "description" : "Search for entities that match a given sub-string.\n\n---\n\nAlternate route: `/v1/search/`\n\nAlternate route: `/legacy/search/`\n\nAlternate route: `/dev/search/`\n",
        "operationId" : "get_search"
      }
    },
    "/sovereignty/campaigns/" : {
      "get" : {
        "tags" : [ "Sovereignty", "Live" ],
        "summary" : "List sovereignty campaigns",
        "description" : "Shows sovereignty data for campaigns.\n\n---\n\nAlternate route: `/v1/sovereignty/campaigns/`\n\nAlternate route: `/legacy/sovereignty/campaigns/`\n\nAlternate route: `/dev/sovereignty/campaigns/`\n\n\n---\n\nThis route is cached for up to 5 seconds",
        "operationId" : "get_sovereignty_campaigns"
      }
    },
    "/sovereignty/structures/" : {
      "get" : {
        "tags" : [ "Sovereignty", "Live" ],
        "summary" : "List sovereignty structures",
        "description" : "Shows sovereignty data for structures.\n\n---\n\nAlternate route: `/v1/sovereignty/structures/`\n\nAlternate route: `/legacy/sovereignty/structures/`\n\nAlternate route: `/dev/sovereignty/structures/`\n\n\n---\n\nThis route is cached for up to 120 seconds",
        "operationId" : "get_sovereignty_structures"
      }
    },
    "/universe/names/" : {
      "post" : {
        "tags" : [ "Live", "Universe" ],
        "summary" : "Get names and categories for a set of ID's",
        "description" : "Resolve a set of IDs to names and categories. Supported ID's for resolving are: Characters, Corporations, Alliances, Stations, Solar Systems, Constellations, Regions, Types.\n\n---\n\nAlternate route: `/v1/universe/names/`\n\nAlternate route: `/legacy/universe/names/`\n",
        "operationId" : "post_universe_names"
      }
    },
    "/universe/planets/{planet_id}/" : {
      "get" : {
        "tags" : [ "Dummy", "Universe" ],
        "summary" : "Get planet information",
        "description" : "Information on a planet\n\n---\n\nAlternate route: `/v1/universe/planets/{planet_id}/`\n\nAlternate route: `/legacy/universe/planets/{planet_id}/`\n\nAlternate route: `/dev/universe/planets/{planet_id}/`\n",
        "operationId" : "get_universe_planets_planet_id"
      }
    },
    "/universe/stations/{station_id}/" : {
      "get" : {
        "tags" : [ "Live", "Universe" ],
        "summary" : "Get station information",
        "description" : "Public information on stations\n\n---\n\nAlternate route: `/v1/universe/stations/{station_id}/`\n\nAlternate route: `/legacy/universe/stations/{station_id}/`\n\nAlternate route: `/dev/universe/stations/{station_id}/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_universe_stations_station_id"
      }
    },
    "/universe/structures/" : {
      "get" : {
        "tags" : [ "Live", "Universe" ],
        "summary" : "List all public structures",
        "description" : "List all public structures\n\n---\n\nAlternate route: `/v1/universe/structures/`\n\nAlternate route: `/legacy/universe/structures/`\n\nAlternate route: `/dev/universe/structures/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_universe_structures"
      }
    },
    "/universe/structures/{structure_id}/" : {
      "get" : {
        "tags" : [ "Live", "Universe" ],
        "summary" : "Get structure information",
        "description" : "Returns information on requested structure, if you are on the ACL. Otherwise, returns \"Forbidden\" for all inputs.\n\n---\n\nAlternate route: `/v1/universe/structures/{structure_id}/`\n\nAlternate route: `/legacy/universe/structures/{structure_id}/`\n\nAlternate route: `/dev/universe/structures/{structure_id}/`\n",
        "operationId" : "get_universe_structures_structure_id",
        "security" : [ {
          "evesso" : [ "esi-universe.read_structures.v1" ]
        } ]
      }
    },
    "/universe/systems/{system_id}/" : {
      "get" : {
        "tags" : [ "Live", "Universe" ],
        "summary" : "Get solar system information",
        "description" : "Information on solar systems\n\n---\n\nAlternate route: `/v1/universe/systems/{system_id}/`\n\nAlternate route: `/legacy/universe/systems/{system_id}/`\n\nAlternate route: `/dev/universe/systems/{system_id}/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_universe_systems_system_id"
      }
    },
    "/universe/types/{type_id}/" : {
      "get" : {
        "tags" : [ "Live", "Universe" ],
        "summary" : "Get type information",
        "description" : "Get information on a type\n\n---\n\nAlternate route: `/v1/universe/types/{type_id}/`\n\nAlternate route: `/legacy/universe/types/{type_id}/`\n\nAlternate route: `/dev/universe/types/{type_id}/`\n\n\n---\n\nThis route is cached for up to 3600 seconds",
        "operationId" : "get_universe_types_type_id"
      }
    }
  },
  "securityDefinitions" : {
    "evesso" : {
      "type" : "oauth2",
      "authorizationUrl" : "https://login.eveonline.com/oauth/authorize",
      "flow" : "implicit",
      "scopes" : {
        "esi-bookmarks.read_character_bookmarks.v1" : "EVE SSO scope esi-bookmarks.read_character_bookmarks.v1",
        "esi-calendar.read_calendar_events.v1" : "EVE SSO scope esi-calendar.read_calendar_events.v1",
        "esi-calendar.respond_calendar_events.v1" : "EVE SSO scope esi-calendar.respond_calendar_events.v1",
        "esi-characters.read_contacts.v1" : "EVE SSO scope esi-characters.read_contacts.v1",
        "esi-clones.read_clones.v1" : "EVE SSO scope esi-clones.read_clones.v1",
        "esi-corporations.read_corporation_membership.v1" : "EVE SSO scope esi-corporations.read_corporation_membership.v1",
        "esi-killmails.read_killmails.v1" : "EVE SSO scope esi-killmails.read_killmails.v1",
        "esi-location.read_location.v1" : "EVE SSO scope esi-location.read_location.v1",
        "esi-location.read_ship_type.v1" : "EVE SSO scope esi-location.read_ship_type.v1",
        "esi-mail.organize_mail.v1" : "EVE SSO scope esi-mail.organize_mail.v1",
        "esi-mail.read_mail.v1" : "EVE SSO scope esi-mail.read_mail.v1",
        "esi-mail.send_mail.v1" : "EVE SSO scope esi-mail.send_mail.v1",
        "esi-search.search_structures.v1" : "EVE SSO scope esi-search.search_structures.v1",
        "esi-skills.read_skillqueue.v1" : "EVE SSO scope esi-skills.read_skillqueue.v1",
        "esi-skills.read_skills.v1" : "EVE SSO scope esi-skills.read_skills.v1",
        "esi-universe.read_structures.v1" : "EVE SSO scope esi-universe.read_structures.v1",
        "esi-wallet.read_character_wallet.v1" : "EVE SSO scope esi-wallet.read_character_wallet.v1"
      }
    }
  }
}