// Code generated by go-swagger; DO NOT EDIT.

package wars

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/evecentral/esiapi/models"
)

// GetWarsReader is a Reader for the GetWars structure.
type GetWarsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWarsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetWarsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewGetWarsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetWarsOK creates a GetWarsOK with default headers values
func NewGetWarsOK() *GetWarsOK {
	return &GetWarsOK{}
}

/*GetWarsOK handles this case with default header values.

A list of war IDs, in decending order by war_id.
*/
type GetWarsOK struct {
	/*The caching mechanism used
	 */
	CacheControl string
	/*RFC7231 formatted datetime string
	 */
	Expires string
	/*RFC7231 formatted datetime string
	 */
	LastModified string

	Payload []int32
}

func (o *GetWarsOK) Error() string {
	return fmt.Sprintf("[GET /wars/][%d] getWarsOK  %+v", 200, o.Payload)
}

func (o *GetWarsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Cache-Control
	o.CacheControl = response.GetHeader("Cache-Control")

	// response header Expires
	o.Expires = response.GetHeader("Expires")

	// response header Last-Modified
	o.LastModified = response.GetHeader("Last-Modified")

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetWarsInternalServerError creates a GetWarsInternalServerError with default headers values
func NewGetWarsInternalServerError() *GetWarsInternalServerError {
	return &GetWarsInternalServerError{}
}

/*GetWarsInternalServerError handles this case with default header values.

Internal server error
*/
type GetWarsInternalServerError struct {
	Payload *models.InternalServerError
}

func (o *GetWarsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /wars/][%d] getWarsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetWarsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
