// Code generated by go-swagger; DO NOT EDIT.

package universe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/evecentral/esiapi/models"
)

// PostUniverseNamesReader is a Reader for the PostUniverseNames structure.
type PostUniverseNamesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostUniverseNamesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostUniverseNamesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostUniverseNamesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostUniverseNamesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 420:
		result := NewPostUniverseNamesEnhanceYourCalm()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewPostUniverseNamesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewPostUniverseNamesServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 504:
		result := NewPostUniverseNamesGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostUniverseNamesOK creates a PostUniverseNamesOK with default headers values
func NewPostUniverseNamesOK() *PostUniverseNamesOK {
	return &PostUniverseNamesOK{}
}

/*PostUniverseNamesOK handles this case with default header values.

List of id/name associations for a set of ID's. All ID's must resolve to a name, or nothing will be returned.
*/
type PostUniverseNamesOK struct {
	Payload []*models.PostUniverseNamesOKBodyItems
}

func (o *PostUniverseNamesOK) Error() string {
	return fmt.Sprintf("[POST /universe/names/][%d] postUniverseNamesOK  %+v", 200, o.Payload)
}

func (o *PostUniverseNamesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUniverseNamesBadRequest creates a PostUniverseNamesBadRequest with default headers values
func NewPostUniverseNamesBadRequest() *PostUniverseNamesBadRequest {
	return &PostUniverseNamesBadRequest{}
}

/*PostUniverseNamesBadRequest handles this case with default header values.

Bad request
*/
type PostUniverseNamesBadRequest struct {
	Payload *models.BadRequest
}

func (o *PostUniverseNamesBadRequest) Error() string {
	return fmt.Sprintf("[POST /universe/names/][%d] postUniverseNamesBadRequest  %+v", 400, o.Payload)
}

func (o *PostUniverseNamesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUniverseNamesNotFound creates a PostUniverseNamesNotFound with default headers values
func NewPostUniverseNamesNotFound() *PostUniverseNamesNotFound {
	return &PostUniverseNamesNotFound{}
}

/*PostUniverseNamesNotFound handles this case with default header values.

Ensure all IDs are valid before resolving.
*/
type PostUniverseNamesNotFound struct {
	Payload *models.PostUniverseNamesNotFoundBody
}

func (o *PostUniverseNamesNotFound) Error() string {
	return fmt.Sprintf("[POST /universe/names/][%d] postUniverseNamesNotFound  %+v", 404, o.Payload)
}

func (o *PostUniverseNamesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PostUniverseNamesNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUniverseNamesEnhanceYourCalm creates a PostUniverseNamesEnhanceYourCalm with default headers values
func NewPostUniverseNamesEnhanceYourCalm() *PostUniverseNamesEnhanceYourCalm {
	return &PostUniverseNamesEnhanceYourCalm{}
}

/*PostUniverseNamesEnhanceYourCalm handles this case with default header values.

Error limited
*/
type PostUniverseNamesEnhanceYourCalm struct {
	Payload *models.ErrorLimited
}

func (o *PostUniverseNamesEnhanceYourCalm) Error() string {
	return fmt.Sprintf("[POST /universe/names/][%d] postUniverseNamesEnhanceYourCalm  %+v", 420, o.Payload)
}

func (o *PostUniverseNamesEnhanceYourCalm) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorLimited)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUniverseNamesInternalServerError creates a PostUniverseNamesInternalServerError with default headers values
func NewPostUniverseNamesInternalServerError() *PostUniverseNamesInternalServerError {
	return &PostUniverseNamesInternalServerError{}
}

/*PostUniverseNamesInternalServerError handles this case with default header values.

Internal server error
*/
type PostUniverseNamesInternalServerError struct {
	Payload *models.InternalServerError
}

func (o *PostUniverseNamesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /universe/names/][%d] postUniverseNamesInternalServerError  %+v", 500, o.Payload)
}

func (o *PostUniverseNamesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUniverseNamesServiceUnavailable creates a PostUniverseNamesServiceUnavailable with default headers values
func NewPostUniverseNamesServiceUnavailable() *PostUniverseNamesServiceUnavailable {
	return &PostUniverseNamesServiceUnavailable{}
}

/*PostUniverseNamesServiceUnavailable handles this case with default header values.

Service unavailable
*/
type PostUniverseNamesServiceUnavailable struct {
	Payload *models.ServiceUnavailable
}

func (o *PostUniverseNamesServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /universe/names/][%d] postUniverseNamesServiceUnavailable  %+v", 503, o.Payload)
}

func (o *PostUniverseNamesServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceUnavailable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostUniverseNamesGatewayTimeout creates a PostUniverseNamesGatewayTimeout with default headers values
func NewPostUniverseNamesGatewayTimeout() *PostUniverseNamesGatewayTimeout {
	return &PostUniverseNamesGatewayTimeout{}
}

/*PostUniverseNamesGatewayTimeout handles this case with default header values.

Gateway timeout
*/
type PostUniverseNamesGatewayTimeout struct {
	Payload *models.GatewayTimeout
}

func (o *PostUniverseNamesGatewayTimeout) Error() string {
	return fmt.Sprintf("[POST /universe/names/][%d] postUniverseNamesGatewayTimeout  %+v", 504, o.Payload)
}

func (o *PostUniverseNamesGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatewayTimeout)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
