// Code generated by go-swagger; DO NOT EDIT.

package killmails

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/evecentral/esiapi/models"
)

// GetCharactersCharacterIDKillmailsRecentReader is a Reader for the GetCharactersCharacterIDKillmailsRecent structure.
type GetCharactersCharacterIDKillmailsRecentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCharactersCharacterIDKillmailsRecentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCharactersCharacterIDKillmailsRecentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 304:
		result := NewGetCharactersCharacterIDKillmailsRecentNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 400:
		result := NewGetCharactersCharacterIDKillmailsRecentBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetCharactersCharacterIDKillmailsRecentUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetCharactersCharacterIDKillmailsRecentForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 420:
		result := NewGetCharactersCharacterIDKillmailsRecentEnhanceYourCalm()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetCharactersCharacterIDKillmailsRecentInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewGetCharactersCharacterIDKillmailsRecentServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 504:
		result := NewGetCharactersCharacterIDKillmailsRecentGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCharactersCharacterIDKillmailsRecentOK creates a GetCharactersCharacterIDKillmailsRecentOK with default headers values
func NewGetCharactersCharacterIDKillmailsRecentOK() *GetCharactersCharacterIDKillmailsRecentOK {
	return &GetCharactersCharacterIDKillmailsRecentOK{
		XPages: 1,
	}
}

/*GetCharactersCharacterIDKillmailsRecentOK handles this case with default header values.

A list of killmail IDs and hashes
*/
type GetCharactersCharacterIDKillmailsRecentOK struct {
	/*The caching mechanism used
	 */
	CacheControl string
	/*RFC7232 compliant entity tag
	 */
	ETag string
	/*RFC7231 formatted datetime string
	 */
	Expires string
	/*RFC7231 formatted datetime string
	 */
	LastModified string
	/*Maximum page number
	 */
	XPages int32

	Payload []*models.GetCharactersCharacterIDKillmailsRecentOKBodyItems
}

func (o *GetCharactersCharacterIDKillmailsRecentOK) Error() string {
	return fmt.Sprintf("[GET /characters/{character_id}/killmails/recent/][%d] getCharactersCharacterIdKillmailsRecentOK  %+v", 200, o.Payload)
}

func (o *GetCharactersCharacterIDKillmailsRecentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Cache-Control
	o.CacheControl = response.GetHeader("Cache-Control")

	// response header ETag
	o.ETag = response.GetHeader("ETag")

	// response header Expires
	o.Expires = response.GetHeader("Expires")

	// response header Last-Modified
	o.LastModified = response.GetHeader("Last-Modified")

	// response header X-Pages
	xPages, err := swag.ConvertInt32(response.GetHeader("X-Pages"))
	if err != nil {
		return errors.InvalidType("X-Pages", "header", "int32", response.GetHeader("X-Pages"))
	}
	o.XPages = xPages

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDKillmailsRecentNotModified creates a GetCharactersCharacterIDKillmailsRecentNotModified with default headers values
func NewGetCharactersCharacterIDKillmailsRecentNotModified() *GetCharactersCharacterIDKillmailsRecentNotModified {
	return &GetCharactersCharacterIDKillmailsRecentNotModified{}
}

/*GetCharactersCharacterIDKillmailsRecentNotModified handles this case with default header values.

Not modified
*/
type GetCharactersCharacterIDKillmailsRecentNotModified struct {
	/*The caching mechanism used
	 */
	CacheControl string
	/*RFC7232 compliant entity tag
	 */
	ETag string
	/*RFC7231 formatted datetime string
	 */
	Expires string
	/*RFC7231 formatted datetime string
	 */
	LastModified string
}

func (o *GetCharactersCharacterIDKillmailsRecentNotModified) Error() string {
	return fmt.Sprintf("[GET /characters/{character_id}/killmails/recent/][%d] getCharactersCharacterIdKillmailsRecentNotModified ", 304)
}

func (o *GetCharactersCharacterIDKillmailsRecentNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Cache-Control
	o.CacheControl = response.GetHeader("Cache-Control")

	// response header ETag
	o.ETag = response.GetHeader("ETag")

	// response header Expires
	o.Expires = response.GetHeader("Expires")

	// response header Last-Modified
	o.LastModified = response.GetHeader("Last-Modified")

	return nil
}

// NewGetCharactersCharacterIDKillmailsRecentBadRequest creates a GetCharactersCharacterIDKillmailsRecentBadRequest with default headers values
func NewGetCharactersCharacterIDKillmailsRecentBadRequest() *GetCharactersCharacterIDKillmailsRecentBadRequest {
	return &GetCharactersCharacterIDKillmailsRecentBadRequest{}
}

/*GetCharactersCharacterIDKillmailsRecentBadRequest handles this case with default header values.

Bad request
*/
type GetCharactersCharacterIDKillmailsRecentBadRequest struct {
	Payload *models.BadRequest
}

func (o *GetCharactersCharacterIDKillmailsRecentBadRequest) Error() string {
	return fmt.Sprintf("[GET /characters/{character_id}/killmails/recent/][%d] getCharactersCharacterIdKillmailsRecentBadRequest  %+v", 400, o.Payload)
}

func (o *GetCharactersCharacterIDKillmailsRecentBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDKillmailsRecentUnauthorized creates a GetCharactersCharacterIDKillmailsRecentUnauthorized with default headers values
func NewGetCharactersCharacterIDKillmailsRecentUnauthorized() *GetCharactersCharacterIDKillmailsRecentUnauthorized {
	return &GetCharactersCharacterIDKillmailsRecentUnauthorized{}
}

/*GetCharactersCharacterIDKillmailsRecentUnauthorized handles this case with default header values.

Unauthorized
*/
type GetCharactersCharacterIDKillmailsRecentUnauthorized struct {
	Payload *models.Unauthorized
}

func (o *GetCharactersCharacterIDKillmailsRecentUnauthorized) Error() string {
	return fmt.Sprintf("[GET /characters/{character_id}/killmails/recent/][%d] getCharactersCharacterIdKillmailsRecentUnauthorized  %+v", 401, o.Payload)
}

func (o *GetCharactersCharacterIDKillmailsRecentUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Unauthorized)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDKillmailsRecentForbidden creates a GetCharactersCharacterIDKillmailsRecentForbidden with default headers values
func NewGetCharactersCharacterIDKillmailsRecentForbidden() *GetCharactersCharacterIDKillmailsRecentForbidden {
	return &GetCharactersCharacterIDKillmailsRecentForbidden{}
}

/*GetCharactersCharacterIDKillmailsRecentForbidden handles this case with default header values.

Forbidden
*/
type GetCharactersCharacterIDKillmailsRecentForbidden struct {
	Payload *models.Forbidden
}

func (o *GetCharactersCharacterIDKillmailsRecentForbidden) Error() string {
	return fmt.Sprintf("[GET /characters/{character_id}/killmails/recent/][%d] getCharactersCharacterIdKillmailsRecentForbidden  %+v", 403, o.Payload)
}

func (o *GetCharactersCharacterIDKillmailsRecentForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Forbidden)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDKillmailsRecentEnhanceYourCalm creates a GetCharactersCharacterIDKillmailsRecentEnhanceYourCalm with default headers values
func NewGetCharactersCharacterIDKillmailsRecentEnhanceYourCalm() *GetCharactersCharacterIDKillmailsRecentEnhanceYourCalm {
	return &GetCharactersCharacterIDKillmailsRecentEnhanceYourCalm{}
}

/*GetCharactersCharacterIDKillmailsRecentEnhanceYourCalm handles this case with default header values.

Error limited
*/
type GetCharactersCharacterIDKillmailsRecentEnhanceYourCalm struct {
	Payload *models.ErrorLimited
}

func (o *GetCharactersCharacterIDKillmailsRecentEnhanceYourCalm) Error() string {
	return fmt.Sprintf("[GET /characters/{character_id}/killmails/recent/][%d] getCharactersCharacterIdKillmailsRecentEnhanceYourCalm  %+v", 420, o.Payload)
}

func (o *GetCharactersCharacterIDKillmailsRecentEnhanceYourCalm) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorLimited)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDKillmailsRecentInternalServerError creates a GetCharactersCharacterIDKillmailsRecentInternalServerError with default headers values
func NewGetCharactersCharacterIDKillmailsRecentInternalServerError() *GetCharactersCharacterIDKillmailsRecentInternalServerError {
	return &GetCharactersCharacterIDKillmailsRecentInternalServerError{}
}

/*GetCharactersCharacterIDKillmailsRecentInternalServerError handles this case with default header values.

Internal server error
*/
type GetCharactersCharacterIDKillmailsRecentInternalServerError struct {
	Payload *models.InternalServerError
}

func (o *GetCharactersCharacterIDKillmailsRecentInternalServerError) Error() string {
	return fmt.Sprintf("[GET /characters/{character_id}/killmails/recent/][%d] getCharactersCharacterIdKillmailsRecentInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCharactersCharacterIDKillmailsRecentInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDKillmailsRecentServiceUnavailable creates a GetCharactersCharacterIDKillmailsRecentServiceUnavailable with default headers values
func NewGetCharactersCharacterIDKillmailsRecentServiceUnavailable() *GetCharactersCharacterIDKillmailsRecentServiceUnavailable {
	return &GetCharactersCharacterIDKillmailsRecentServiceUnavailable{}
}

/*GetCharactersCharacterIDKillmailsRecentServiceUnavailable handles this case with default header values.

Service unavailable
*/
type GetCharactersCharacterIDKillmailsRecentServiceUnavailable struct {
	Payload *models.ServiceUnavailable
}

func (o *GetCharactersCharacterIDKillmailsRecentServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /characters/{character_id}/killmails/recent/][%d] getCharactersCharacterIdKillmailsRecentServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetCharactersCharacterIDKillmailsRecentServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceUnavailable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDKillmailsRecentGatewayTimeout creates a GetCharactersCharacterIDKillmailsRecentGatewayTimeout with default headers values
func NewGetCharactersCharacterIDKillmailsRecentGatewayTimeout() *GetCharactersCharacterIDKillmailsRecentGatewayTimeout {
	return &GetCharactersCharacterIDKillmailsRecentGatewayTimeout{}
}

/*GetCharactersCharacterIDKillmailsRecentGatewayTimeout handles this case with default header values.

Gateway timeout
*/
type GetCharactersCharacterIDKillmailsRecentGatewayTimeout struct {
	Payload *models.GatewayTimeout
}

func (o *GetCharactersCharacterIDKillmailsRecentGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /characters/{character_id}/killmails/recent/][%d] getCharactersCharacterIdKillmailsRecentGatewayTimeout  %+v", 504, o.Payload)
}

func (o *GetCharactersCharacterIDKillmailsRecentGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatewayTimeout)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
