// Code generated by go-swagger; DO NOT EDIT.

package corporation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/evecentral/esiapi/models"
)

// GetCorporationsCorporationIDMembertrackingReader is a Reader for the GetCorporationsCorporationIDMembertracking structure.
type GetCorporationsCorporationIDMembertrackingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCorporationsCorporationIDMembertrackingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCorporationsCorporationIDMembertrackingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewGetCorporationsCorporationIDMembertrackingForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetCorporationsCorporationIDMembertrackingInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCorporationsCorporationIDMembertrackingOK creates a GetCorporationsCorporationIDMembertrackingOK with default headers values
func NewGetCorporationsCorporationIDMembertrackingOK() *GetCorporationsCorporationIDMembertrackingOK {
	return &GetCorporationsCorporationIDMembertrackingOK{}
}

/*GetCorporationsCorporationIDMembertrackingOK handles this case with default header values.

List of member character IDs
*/
type GetCorporationsCorporationIDMembertrackingOK struct {
	/*The caching mechanism used
	 */
	CacheControl string
	/*RFC7231 formatted datetime string
	 */
	Expires string
	/*RFC7231 formatted datetime string
	 */
	LastModified string

	Payload []*GetCorporationsCorporationIDMembertrackingOKBodyItems0
}

func (o *GetCorporationsCorporationIDMembertrackingOK) Error() string {
	return fmt.Sprintf("[GET /corporations/{corporation_id}/membertracking/][%d] getCorporationsCorporationIdMembertrackingOK  %+v", 200, o.Payload)
}

func (o *GetCorporationsCorporationIDMembertrackingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Cache-Control
	o.CacheControl = response.GetHeader("Cache-Control")

	// response header Expires
	o.Expires = response.GetHeader("Expires")

	// response header Last-Modified
	o.LastModified = response.GetHeader("Last-Modified")

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorporationsCorporationIDMembertrackingForbidden creates a GetCorporationsCorporationIDMembertrackingForbidden with default headers values
func NewGetCorporationsCorporationIDMembertrackingForbidden() *GetCorporationsCorporationIDMembertrackingForbidden {
	return &GetCorporationsCorporationIDMembertrackingForbidden{}
}

/*GetCorporationsCorporationIDMembertrackingForbidden handles this case with default header values.

Forbidden
*/
type GetCorporationsCorporationIDMembertrackingForbidden struct {
	Payload *models.Forbidden
}

func (o *GetCorporationsCorporationIDMembertrackingForbidden) Error() string {
	return fmt.Sprintf("[GET /corporations/{corporation_id}/membertracking/][%d] getCorporationsCorporationIdMembertrackingForbidden  %+v", 403, o.Payload)
}

func (o *GetCorporationsCorporationIDMembertrackingForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Forbidden)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorporationsCorporationIDMembertrackingInternalServerError creates a GetCorporationsCorporationIDMembertrackingInternalServerError with default headers values
func NewGetCorporationsCorporationIDMembertrackingInternalServerError() *GetCorporationsCorporationIDMembertrackingInternalServerError {
	return &GetCorporationsCorporationIDMembertrackingInternalServerError{}
}

/*GetCorporationsCorporationIDMembertrackingInternalServerError handles this case with default header values.

Internal server error
*/
type GetCorporationsCorporationIDMembertrackingInternalServerError struct {
	Payload *models.InternalServerError
}

func (o *GetCorporationsCorporationIDMembertrackingInternalServerError) Error() string {
	return fmt.Sprintf("[GET /corporations/{corporation_id}/membertracking/][%d] getCorporationsCorporationIdMembertrackingInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCorporationsCorporationIDMembertrackingInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetCorporationsCorporationIDMembertrackingOKBodyItems0 get_corporations_corporation_id_membertracking_200_ok
//
// 200 ok object
swagger:model GetCorporationsCorporationIDMembertrackingOKBodyItems0
*/

type GetCorporationsCorporationIDMembertrackingOKBodyItems0 struct {

	// get_corporations_corporation_id_membertracking_base_id
	//
	// base_id integer
	BaseID int32 `json:"base_id,omitempty"`

	// get_corporations_corporation_id_membertracking_character_id
	//
	// character_id integer
	// Required: true
	CharacterID *int32 `json:"character_id"`

	// get_corporations_corporation_id_membertracking_location_id
	//
	// location_id integer
	LocationID int64 `json:"location_id,omitempty"`

	// get_corporations_corporation_id_membertracking_logoff_date
	//
	// logoff_date string
	LogoffDate strfmt.DateTime `json:"logoff_date,omitempty"`

	// get_corporations_corporation_id_membertracking_logon_date
	//
	// logon_date string
	LogonDate strfmt.DateTime `json:"logon_date,omitempty"`

	// get_corporations_corporation_id_membertracking_ship_type_id
	//
	// ship_type_id integer
	ShipTypeID int32 `json:"ship_type_id,omitempty"`

	// get_corporations_corporation_id_membertracking_start_date
	//
	// start_date string
	StartDate strfmt.DateTime `json:"start_date,omitempty"`
}

/* polymorph GetCorporationsCorporationIDMembertrackingOKBodyItems0 base_id false */

/* polymorph GetCorporationsCorporationIDMembertrackingOKBodyItems0 character_id false */

/* polymorph GetCorporationsCorporationIDMembertrackingOKBodyItems0 location_id false */

/* polymorph GetCorporationsCorporationIDMembertrackingOKBodyItems0 logoff_date false */

/* polymorph GetCorporationsCorporationIDMembertrackingOKBodyItems0 logon_date false */

/* polymorph GetCorporationsCorporationIDMembertrackingOKBodyItems0 ship_type_id false */

/* polymorph GetCorporationsCorporationIDMembertrackingOKBodyItems0 start_date false */

// Validate validates this get corporations corporation ID membertracking o k body items0
func (o *GetCorporationsCorporationIDMembertrackingOKBodyItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCharacterID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCorporationsCorporationIDMembertrackingOKBodyItems0) validateCharacterID(formats strfmt.Registry) error {

	if err := validate.Required("character_id", "body", o.CharacterID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetCorporationsCorporationIDMembertrackingOKBodyItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCorporationsCorporationIDMembertrackingOKBodyItems0) UnmarshalBinary(b []byte) error {
	var res GetCorporationsCorporationIDMembertrackingOKBodyItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
