// Code generated by go-swagger; DO NOT EDIT.

package corporation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/evecentral/esiapi/models"
)

// GetCorporationsCorporationIDRolesReader is a Reader for the GetCorporationsCorporationIDRoles structure.
type GetCorporationsCorporationIDRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCorporationsCorporationIDRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCorporationsCorporationIDRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 304:
		result := NewGetCorporationsCorporationIDRolesNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 400:
		result := NewGetCorporationsCorporationIDRolesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetCorporationsCorporationIDRolesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetCorporationsCorporationIDRolesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 420:
		result := NewGetCorporationsCorporationIDRolesEnhanceYourCalm()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetCorporationsCorporationIDRolesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewGetCorporationsCorporationIDRolesServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 504:
		result := NewGetCorporationsCorporationIDRolesGatewayTimeout()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCorporationsCorporationIDRolesOK creates a GetCorporationsCorporationIDRolesOK with default headers values
func NewGetCorporationsCorporationIDRolesOK() *GetCorporationsCorporationIDRolesOK {
	return &GetCorporationsCorporationIDRolesOK{}
}

/*GetCorporationsCorporationIDRolesOK handles this case with default header values.

List of member character ID's and roles
*/
type GetCorporationsCorporationIDRolesOK struct {
	/*The caching mechanism used
	 */
	CacheControl string
	/*RFC7232 compliant entity tag
	 */
	ETag string
	/*RFC7231 formatted datetime string
	 */
	Expires string
	/*RFC7231 formatted datetime string
	 */
	LastModified string

	Payload []*models.GetCorporationsCorporationIDRolesOKBodyItems
}

func (o *GetCorporationsCorporationIDRolesOK) Error() string {
	return fmt.Sprintf("[GET /corporations/{corporation_id}/roles/][%d] getCorporationsCorporationIdRolesOK  %+v", 200, o.Payload)
}

func (o *GetCorporationsCorporationIDRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Cache-Control
	o.CacheControl = response.GetHeader("Cache-Control")

	// response header ETag
	o.ETag = response.GetHeader("ETag")

	// response header Expires
	o.Expires = response.GetHeader("Expires")

	// response header Last-Modified
	o.LastModified = response.GetHeader("Last-Modified")

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorporationsCorporationIDRolesNotModified creates a GetCorporationsCorporationIDRolesNotModified with default headers values
func NewGetCorporationsCorporationIDRolesNotModified() *GetCorporationsCorporationIDRolesNotModified {
	return &GetCorporationsCorporationIDRolesNotModified{}
}

/*GetCorporationsCorporationIDRolesNotModified handles this case with default header values.

Not modified
*/
type GetCorporationsCorporationIDRolesNotModified struct {
	/*The caching mechanism used
	 */
	CacheControl string
	/*RFC7232 compliant entity tag
	 */
	ETag string
	/*RFC7231 formatted datetime string
	 */
	Expires string
	/*RFC7231 formatted datetime string
	 */
	LastModified string
}

func (o *GetCorporationsCorporationIDRolesNotModified) Error() string {
	return fmt.Sprintf("[GET /corporations/{corporation_id}/roles/][%d] getCorporationsCorporationIdRolesNotModified ", 304)
}

func (o *GetCorporationsCorporationIDRolesNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Cache-Control
	o.CacheControl = response.GetHeader("Cache-Control")

	// response header ETag
	o.ETag = response.GetHeader("ETag")

	// response header Expires
	o.Expires = response.GetHeader("Expires")

	// response header Last-Modified
	o.LastModified = response.GetHeader("Last-Modified")

	return nil
}

// NewGetCorporationsCorporationIDRolesBadRequest creates a GetCorporationsCorporationIDRolesBadRequest with default headers values
func NewGetCorporationsCorporationIDRolesBadRequest() *GetCorporationsCorporationIDRolesBadRequest {
	return &GetCorporationsCorporationIDRolesBadRequest{}
}

/*GetCorporationsCorporationIDRolesBadRequest handles this case with default header values.

Bad request
*/
type GetCorporationsCorporationIDRolesBadRequest struct {
	Payload *models.BadRequest
}

func (o *GetCorporationsCorporationIDRolesBadRequest) Error() string {
	return fmt.Sprintf("[GET /corporations/{corporation_id}/roles/][%d] getCorporationsCorporationIdRolesBadRequest  %+v", 400, o.Payload)
}

func (o *GetCorporationsCorporationIDRolesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorporationsCorporationIDRolesUnauthorized creates a GetCorporationsCorporationIDRolesUnauthorized with default headers values
func NewGetCorporationsCorporationIDRolesUnauthorized() *GetCorporationsCorporationIDRolesUnauthorized {
	return &GetCorporationsCorporationIDRolesUnauthorized{}
}

/*GetCorporationsCorporationIDRolesUnauthorized handles this case with default header values.

Unauthorized
*/
type GetCorporationsCorporationIDRolesUnauthorized struct {
	Payload *models.Unauthorized
}

func (o *GetCorporationsCorporationIDRolesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /corporations/{corporation_id}/roles/][%d] getCorporationsCorporationIdRolesUnauthorized  %+v", 401, o.Payload)
}

func (o *GetCorporationsCorporationIDRolesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Unauthorized)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorporationsCorporationIDRolesForbidden creates a GetCorporationsCorporationIDRolesForbidden with default headers values
func NewGetCorporationsCorporationIDRolesForbidden() *GetCorporationsCorporationIDRolesForbidden {
	return &GetCorporationsCorporationIDRolesForbidden{}
}

/*GetCorporationsCorporationIDRolesForbidden handles this case with default header values.

Forbidden
*/
type GetCorporationsCorporationIDRolesForbidden struct {
	Payload *models.Forbidden
}

func (o *GetCorporationsCorporationIDRolesForbidden) Error() string {
	return fmt.Sprintf("[GET /corporations/{corporation_id}/roles/][%d] getCorporationsCorporationIdRolesForbidden  %+v", 403, o.Payload)
}

func (o *GetCorporationsCorporationIDRolesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Forbidden)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorporationsCorporationIDRolesEnhanceYourCalm creates a GetCorporationsCorporationIDRolesEnhanceYourCalm with default headers values
func NewGetCorporationsCorporationIDRolesEnhanceYourCalm() *GetCorporationsCorporationIDRolesEnhanceYourCalm {
	return &GetCorporationsCorporationIDRolesEnhanceYourCalm{}
}

/*GetCorporationsCorporationIDRolesEnhanceYourCalm handles this case with default header values.

Error limited
*/
type GetCorporationsCorporationIDRolesEnhanceYourCalm struct {
	Payload *models.ErrorLimited
}

func (o *GetCorporationsCorporationIDRolesEnhanceYourCalm) Error() string {
	return fmt.Sprintf("[GET /corporations/{corporation_id}/roles/][%d] getCorporationsCorporationIdRolesEnhanceYourCalm  %+v", 420, o.Payload)
}

func (o *GetCorporationsCorporationIDRolesEnhanceYourCalm) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorLimited)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorporationsCorporationIDRolesInternalServerError creates a GetCorporationsCorporationIDRolesInternalServerError with default headers values
func NewGetCorporationsCorporationIDRolesInternalServerError() *GetCorporationsCorporationIDRolesInternalServerError {
	return &GetCorporationsCorporationIDRolesInternalServerError{}
}

/*GetCorporationsCorporationIDRolesInternalServerError handles this case with default header values.

Internal server error
*/
type GetCorporationsCorporationIDRolesInternalServerError struct {
	Payload *models.InternalServerError
}

func (o *GetCorporationsCorporationIDRolesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /corporations/{corporation_id}/roles/][%d] getCorporationsCorporationIdRolesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCorporationsCorporationIDRolesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorporationsCorporationIDRolesServiceUnavailable creates a GetCorporationsCorporationIDRolesServiceUnavailable with default headers values
func NewGetCorporationsCorporationIDRolesServiceUnavailable() *GetCorporationsCorporationIDRolesServiceUnavailable {
	return &GetCorporationsCorporationIDRolesServiceUnavailable{}
}

/*GetCorporationsCorporationIDRolesServiceUnavailable handles this case with default header values.

Service unavailable
*/
type GetCorporationsCorporationIDRolesServiceUnavailable struct {
	Payload *models.ServiceUnavailable
}

func (o *GetCorporationsCorporationIDRolesServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /corporations/{corporation_id}/roles/][%d] getCorporationsCorporationIdRolesServiceUnavailable  %+v", 503, o.Payload)
}

func (o *GetCorporationsCorporationIDRolesServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceUnavailable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCorporationsCorporationIDRolesGatewayTimeout creates a GetCorporationsCorporationIDRolesGatewayTimeout with default headers values
func NewGetCorporationsCorporationIDRolesGatewayTimeout() *GetCorporationsCorporationIDRolesGatewayTimeout {
	return &GetCorporationsCorporationIDRolesGatewayTimeout{}
}

/*GetCorporationsCorporationIDRolesGatewayTimeout handles this case with default header values.

Gateway timeout
*/
type GetCorporationsCorporationIDRolesGatewayTimeout struct {
	Payload *models.GatewayTimeout
}

func (o *GetCorporationsCorporationIDRolesGatewayTimeout) Error() string {
	return fmt.Sprintf("[GET /corporations/{corporation_id}/roles/][%d] getCorporationsCorporationIdRolesGatewayTimeout  %+v", 504, o.Payload)
}

func (o *GetCorporationsCorporationIDRolesGatewayTimeout) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GatewayTimeout)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
