// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetCharactersCharacterIDSkillsOKBody get_characters_character_id_skills_ok
//
// 200 ok object
// swagger:model getCharactersCharacterIdSkillsOKBody
type GetCharactersCharacterIDSkillsOKBody struct {

	// get_characters_character_id_skills_skills
	//
	// skills array
	// Required: true
	// Max Items: 1000
	Skills []*GetCharactersCharacterIDSkillsOKBodySkillsItems `json:"skills"`

	// get_characters_character_id_skills_total_sp
	//
	// total_sp integer
	// Required: true
	TotalSp *int64 `json:"total_sp"`

	// get_characters_character_id_skills_unallocated_sp
	//
	// Skill points available to be assigned
	UnallocatedSp int32 `json:"unallocated_sp,omitempty"`
}

// Validate validates this get characters character Id skills o k body
func (m *GetCharactersCharacterIDSkillsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSkills(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalSp(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetCharactersCharacterIDSkillsOKBody) validateSkills(formats strfmt.Registry) error {

	if err := validate.Required("skills", "body", m.Skills); err != nil {
		return err
	}

	iSkillsSize := int64(len(m.Skills))

	if err := validate.MaxItems("skills", "body", iSkillsSize, 1000); err != nil {
		return err
	}

	for i := 0; i < len(m.Skills); i++ {
		if swag.IsZero(m.Skills[i]) { // not required
			continue
		}

		if m.Skills[i] != nil {
			if err := m.Skills[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("skills" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *GetCharactersCharacterIDSkillsOKBody) validateTotalSp(formats strfmt.Registry) error {

	if err := validate.Required("total_sp", "body", m.TotalSp); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetCharactersCharacterIDSkillsOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetCharactersCharacterIDSkillsOKBody) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDSkillsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
