// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GetFwLeaderboardsCorporationsOKBodyVictoryPointsActiveTotalItems get_fw_leaderboards_corporations_active_total_active_total_1
//
// active_total object
// swagger:model getFwLeaderboardsCorporationsOKBodyVictoryPointsActiveTotalItems
type GetFwLeaderboardsCorporationsOKBodyVictoryPointsActiveTotalItems struct {

	// get_fw_leaderboards_corporations_active_total_amount
	//
	// Amount of victory points
	Amount int32 `json:"amount,omitempty"`

	// get_fw_leaderboards_corporations_active_total_corporation_id
	//
	// corporation_id integer
	CorporationID int32 `json:"corporation_id,omitempty"`
}

// Validate validates this get fw leaderboards corporations o k body victory points active total items
func (m *GetFwLeaderboardsCorporationsOKBodyVictoryPointsActiveTotalItems) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetFwLeaderboardsCorporationsOKBodyVictoryPointsActiveTotalItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetFwLeaderboardsCorporationsOKBodyVictoryPointsActiveTotalItems) UnmarshalBinary(b []byte) error {
	var res GetFwLeaderboardsCorporationsOKBodyVictoryPointsActiveTotalItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
