package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// GetCorporationsCorporationIDMembersForbidden Forbidden
// swagger:model get_corporations_corporation_id_members_forbidden
type GetCorporationsCorporationIDMembersForbidden struct {

	// get_corporations_corporation_id_members_403_forbidden
	//
	// Forbidden message
	Error string `json:"error,omitempty"`
}

// Validate validates this get corporations corporation id members forbidden
func (m *GetCorporationsCorporationIDMembersForbidden) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
