// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetUniverseAncestriesOKBodyItems get_universe_ancestries_200_ok
//
// 200 ok object
// swagger:model getUniverseAncestriesOKBodyItems
type GetUniverseAncestriesOKBodyItems struct {

	// get_universe_ancestries_bloodline_id
	//
	// The bloodline associated with this ancestry
	// Required: true
	BloodlineID *int32 `json:"bloodline_id"`

	// get_universe_ancestries_description
	//
	// description string
	// Required: true
	Description *string `json:"description"`

	// get_universe_ancestries_icon_id
	//
	// icon_id integer
	IconID int32 `json:"icon_id,omitempty"`

	// get_universe_ancestries_id
	//
	// id integer
	// Required: true
	ID *int32 `json:"id"`

	// get_universe_ancestries_name
	//
	// name string
	// Required: true
	Name *string `json:"name"`

	// get_universe_ancestries_short_description
	//
	// short_description string
	ShortDescription string `json:"short_description,omitempty"`
}

// Validate validates this get universe ancestries o k body items
func (m *GetUniverseAncestriesOKBodyItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBloodlineID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetUniverseAncestriesOKBodyItems) validateBloodlineID(formats strfmt.Registry) error {

	if err := validate.Required("bloodline_id", "body", m.BloodlineID); err != nil {
		return err
	}

	return nil
}

func (m *GetUniverseAncestriesOKBodyItems) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *GetUniverseAncestriesOKBodyItems) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *GetUniverseAncestriesOKBodyItems) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetUniverseAncestriesOKBodyItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetUniverseAncestriesOKBodyItems) UnmarshalBinary(b []byte) error {
	var res GetUniverseAncestriesOKBodyItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
