// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PostFleetsFleetIDWingsWingIDSquadsNotFoundBody post_fleets_fleet_id_wings_wing_id_squads_not_found
//
// Not found
// swagger:model postFleetsFleetIdWingsWingIdSquadsNotFoundBody
type PostFleetsFleetIDWingsWingIDSquadsNotFoundBody struct {

	// post_fleets_fleet_id_wings_wing_id_squads_404_not_found
	//
	// Not found message
	Error string `json:"error,omitempty"`
}

// Validate validates this post fleets fleet Id wings wing Id squads not found body
func (m *PostFleetsFleetIDWingsWingIDSquadsNotFoundBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostFleetsFleetIDWingsWingIDSquadsNotFoundBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostFleetsFleetIDWingsWingIDSquadsNotFoundBody) UnmarshalBinary(b []byte) error {
	var res PostFleetsFleetIDWingsWingIDSquadsNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
