// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PostUniverseIdsOKBodyAlliancesItems post_universe_ids_alliance
//
// alliance object
// swagger:model postUniverseIdsOKBodyAlliancesItems
type PostUniverseIdsOKBodyAlliancesItems struct {

	// post_universe_ids_alliance_id
	//
	// id integer
	ID int32 `json:"id,omitempty"`

	// post_universe_ids_alliance_name
	//
	// name string
	Name string `json:"name,omitempty"`
}

// Validate validates this post universe ids o k body alliances items
func (m *PostUniverseIdsOKBodyAlliancesItems) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostUniverseIdsOKBodyAlliancesItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostUniverseIdsOKBodyAlliancesItems) UnmarshalBinary(b []byte) error {
	var res PostUniverseIdsOKBodyAlliancesItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
