package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// PutCharactersCharacterIDCalendarEventIDInternalServerError Internal server error
// swagger:model put_characters_character_id_calendar_event_id_internal_server_error
type PutCharactersCharacterIDCalendarEventIDInternalServerError struct {

	// put_characters_character_id_calendar_event_id_500_internal_server_error
	//
	// Internal server error message
	Error string `json:"error,omitempty"`
}

// Validate validates this put characters character id calendar event id internal server error
func (m *PutCharactersCharacterIDCalendarEventIDInternalServerError) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
